baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
paginate = 2

[[menus.main]]
name = 'Yazılar'
pageRef = '/posts'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
