baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
paginate = 2

[[menus.main]]
name = 'Blog'
pageRef = '/posts'
weight = 10

[[menus.main]]
identifier = 'categories'
name = 'Kategoriler'
pageRef = '/categories'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
